# Generated by Django 4.2.8 on 2024-05-11 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='date_of_birth',
        ),
    ]
